In [1]:
import numpy as np
#s for sequence
s1 = 'ACGGTAC'
s2 = 'ACCCG'

In [2]:
matrix=np.zeros((len(s1)+1, len(s2)+1))

In [3]:
matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
#c for compare
c_matrix=np.zeros((len(s1), len(s2)))
for i in range(len(s1)):
    for j in range(len(s2)):
        if s1[i]==s2[j]:
            c_matrix[i][j]=1
        else:
            c_matrix[i][j]=0


In [5]:
c_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.]])

In [44]:
match_score=1
mismatch_score=-1
gap_penalty=-1

In [45]:
#r for real
def r_matrix(matrix):
    for i in range(len(s1)+1):
        matrix[i][0]=i*gap_penalty
    for j in range(len(s2)+1):
        matrix[0][j]=j*gap_penalty
    for i in range(1,len(s1)+1):
        for j in range(1,len(s2)+1):
                matrix[i][j]=max(matrix[i-1][j-1]+c_matrix[i-1][j-1],matrix[i-1][j]+gap_penalty,matrix[i][j-1]+gap_penalty)
    return(matrix)             

In [46]:
r_matrix(matrix)

array([[ 0., -1., -2., -3., -4., -5.],
       [-1.,  1.,  0., -1., -2., -3.],
       [-2.,  0.,  2.,  1.,  0., -1.],
       [-3., -1.,  1.,  2.,  1.,  1.],
       [-4., -2.,  0.,  1.,  2.,  2.],
       [-5., -3., -1.,  0.,  1.,  2.],
       [-6., -4., -2., -1.,  0.,  1.],
       [-7., -5., -3., -1.,  0.,  0.]])

In [32]:
#agnt for alignment
agntA=""
agntB=""
i=len(s1)
j=len(s2)
while (i >0 or j >0):
    if  (i > 0 and j > 0 and matrix[i][j]== matrix[i-1][j-1]+c_matrix[i-1][j-1]):
        agntA=s1[i-1] + agntA
        agntB=s2[j-1] + agntB
        i=i - 1
        j=j - 1
    elif (i > 0 and matrix[i][j]==matrix[i-1][j] + gap_penalty):
        agntA=s1[i-1] + agntA
        agntB="-" + agntB
        i=i-1
    else:
        agntA="-" + agntA
        agntB=s2[j-1] + agntB
        j=j - 1

In [33]:
agntA

'ACGGTAC'

In [34]:
agntB

'AC--CCG'

In [47]:
######
